### ISSUE TITLE
Is there a better way to add the admin to the backend like using Postman

### ISSUE THREAD

**Issue by eugene254-ship-it** [mayankdrvr/mern_blog#2]
I have tried to login to the backend its not working.

**Comment by mayankdrvr** [comment]
Good question. I had changed the admin password as some user was creating inappropriate blog posts using the admin password and i thought that not disclosing the password publicly would be the responsible thing to do in the interest of creating a healthy user experience for general visitors on the website. If you like, I can send you the admin password on your email etc. for software testing purposes. I will change the admin password after a few days. I am working on a functionality to create new/guest user accounts using Postman but it might take a few months as i am engaged in other work commitments. Thank you for asking the question.

**Comment by eugene254-ship-it** [comment]
ochakoeugene67@gmail.com is my email

**Comment by mayankdrvr** [comment]
I have sent you the requested login credentials. Please check you email inbox. Thank you.
